Repository Strong-Potato/TripVote-FE, pull requests merged in 2024-01, with the labels that each got.

#3 conf: set global style
  package-lock.json
  src/assets/fonts/SUIT-Variable.ttf
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
  src/routes/MainRouter/MainRouter.module.scss
  src/routes/MainRouter/MainRouter.tsx
  src/sass/abstracts/_index.scss
  src/sass/abstracts/_mixin.scss
  src/sass/abstracts/_variables.scss
  src/sass/base/_index.scss
  src/sass/base/_normalize.scss
  src/sass/main.scss
  tsconfig.json
  vite.config.ts
Labels: conf

#5 feat: create GNB
  package-lock.json
  package.json
  src/components/GlobalNavigationBar/GlobalNavigationBar.module.scss
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/main.tsx
  src/routes/Dashboard/Dashboard.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/sass/abstracts/_function.scss
  src/sass/abstracts/_index.scss
  src/sass/abstracts/_placeholders.scss
  src/sass/base/_animation.scss
  src/sass/base/_index.scss
  src/sass/base/_typography.scss
  src/sass/index.scss
  src/sass/main.scss
  vite.config.ts
Labels: feat

#9 Conf: add github actions
  .github/workflows/ci.yml
Labels: docs, conf

#13 Conf: add variables and library
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/sass/abstracts/_variables.scss
  src/sass/base/_normalize.scss
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.json
  vite.config.ts
Labels: conf

#17 Hotfix: replace fontsize
  src/sass/base/_normalize.scss
Labels: hotfix

#15 Feat: set MSW for browser & server #14
  jest.setup.ts
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers/auth.ts
  src/mocks/handlers/index.ts
  src/mocks/server.ts
  tsconfig.jest.json
Labels: feat

#22 Conf: add chakra custom theme #21
  src/main.tsx
  src/sass/chakraCustomTheme.tsx
Labels: conf

#23 Hotfix: remove align-item property in #root
  src/sass/base/_normalize.scss
Labels: hotfix

#25 7 feat create detail page markup
  package-lock.json
  public/mockServiceWorker.js
  src/components/Detail/BottomFixedBtn/BottomFixedBtn.module.scss
  src/components/Detail/BottomFixedBtn/BottomFixedBtn.tsx
  src/components/Detail/Contents/Contents.module.scss
  src/components/Detail/Contents/Contents.tsx
  src/components/Detail/Contents/Information/BasicInformation/BasicInformation.module.scss
  src/components/Detail/Contents/Information/BasicInformation/BasicInformation.tsx
  src/components/Detail/Contents/Information/BasicInformation/Map/Map.module.scss
  src/components/Detail/Contents/Information/BasicInformation/Map/Map.tsx
  src/components/Detail/Contents/Information/Information.module.scss
  src/components/Detail/Contents/Information/Information.tsx
  src/components/Detail/Contents/Information/Others/OtherCard/OtherCard.module.scss
  src/components/Detail/Contents/Information/Others/OtherCard/OtherCard.tsx
  src/components/Detail/Contents/Information/Others/Others.module.scss
  src/components/Detail/Contents/Information/Others/Others.tsx
  src/components/Detail/Contents/Information/Reservation/Reservation.tsx
  src/components/Detail/Contents/Information/ShortReveiws/ShortReviews.module.scss
  src/components/Detail/Contents/Information/ShortReveiws/ShortReviews.tsx
  src/components/Detail/Contents/Reviews/Reviews.tsx
  src/components/Detail/Contents/Reviews/Rviews.module.scss
  src/components/Detail/Main/Main.module.scss
  src/components/Detail/Main/Main.tsx
  src/components/Detail/Main/Swiper/Swiper.module.scss
  src/components/Detail/Main/Swiper/Swiper.tsx
  src/components/Detail/Main/Title/Title.module.scss
  src/components/Detail/Main/Title/Title.tsx
  src/components/Detail/Navigation/Navigation.module.scss
  src/components/Detail/Navigation/Navigation.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.module.scss
  src/components/Review/Review.module.scss
  src/components/Review/Review.tsx
  src/components/Review/ReviewImageSlider/ReviewImageSlider.module.scss
  src/components/Review/ReviewImageSlider/ReviewImageSlider.tsx
  src/hooks/useComponetSize.ts
  src/pages/Detail/Detail.module.scss
  src/pages/Detail/Detail.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/sass/abstracts/_variables.scss
  src/types/detail.ts
Labels: feat

#26 Feat: create sidebar
  package-lock.json
  src/assets/plus.svg
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/SideBar.tsx
  src/components/SideBar/TravelList/TravelList.module.scss
  src/components/SideBar/TravelList/TravelList.tsx
  src/types/sidebar.ts
Labels: feat

#29 Feat: create home
  public/mapIconHome.png
  public/tripVoteLogoHome.png
  src/components/GlobalNavigationBar/GlobalNavigationBar.module.scss
  src/components/Home/RecommendedItemList/RecommendedItem/RecommendedItem.module.scss
  src/components/Home/RecommendedItemList/RecommendedItem/RecommendedItem.tsx
  src/components/Home/RecommendedItemList/RecommendedItemList.module.scss
  src/components/Home/RecommendedItemList/RecommendedItemList.tsx
  src/components/Home/RecommendedLocationList/RecommendedLocation/RecommendedLocation.module.scss
  src/components/Home/RecommendedLocationList/RecommendedLocation/RecommendedLocation.tsx
  src/components/Home/RecommendedLocationList/RecommendedLocationList.module.scss
  src/components/Home/RecommendedLocationList/RecommendedLocationList.tsx
  src/components/Home/SearchBarAtHome/SearchBarAtHome.module.scss
  src/components/Home/SearchBarAtHome/SearchBarAtHome.tsx
  src/components/Home/TabBar/TabBar.module.scss
  src/components/Home/TabBar/TabBar.tsx
  src/components/Home/TripSpaceAtHome/TripSpaceAtHome.module.scss
  src/components/Home/TripSpaceAtHome/TripSpaceAtHome.tsx
  src/components/Home/TripSpaceAtHome/TripSpaceItem/TripSpaceItem.module.scss
  src/components/Home/TripSpaceAtHome/TripSpaceItem/TripSpaceItem.tsx
  src/components/Home/VoteAtHome/VoteAtHome.module.scss
  src/components/Home/VoteAtHome/VoteAtHome.tsx
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.module.scss
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.tsx
  src/components/Home/VoteAtHome/VoteCard/CardNull/CardNull.module.scss
  src/components/Home/VoteAtHome/VoteCard/CardNull/CardNull.tsx
  src/mocks/handlers/home.ts
  src/mocks/handlers/index.ts
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
  src/types/home.ts
Labels: feat

#31 Feat: markup vote detail page and add common button style in chakra
  package-lock.json
  public/mockServiceWorker.js
  src/assets/ic_vote.svg
  src/components/Vote/CreatVoteTitleModal/CreatVoteTitleModal.module.scss
  src/components/Vote/CreatVoteTitleModal/CreatVoteTitleModal.tsx
  src/components/Vote/VoteCandidateItem/VoteCandidateItem.module.scss
  src/components/Vote/VoteCandidateItem/VoteCandidateItem.tsx
  src/components/Vote/VoteDetailsBottomButton/VoteDetailsBottomButton.module.scss
  src/components/Vote/VoteDetailsBottomButton/VoteDetailsBottomButton.tsx
  src/components/Vote/VoteDetailsField/VoteDetailsField.module.scss
  src/components/Vote/VoteDetailsField/VoteDetailsField.tsx
  src/components/Vote/VoteDetailsFieldZero/VoteDetailsFieldZero.module.scss
  src/components/Vote/VoteDetailsFieldZero/VoteDetailsFieldZero.tsx
  src/components/Vote/VoteDetailsHeader/VoteDetailsHeader.module.scss
  src/components/Vote/VoteDetailsHeader/VoteDetailsHeader.tsx
  src/pages/VoteDetail/VoteDetail.module.scss
  src/pages/VoteDetail/VoteDetail.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/sass/abstracts/_variables.scss
  src/sass/chakraCustomTheme.tsx
Labels: feat, conf

#35 feat: create alarm page #28
  src/components/Alarm/Back/Back.module.scss
  src/components/Alarm/Back/Back.tsx
  src/components/Alarm/TabCapsule/Content/Content.module.scss
  src/components/Alarm/TabCapsule/Content/Content.tsx
  src/components/Alarm/TabCapsule/TabCapsule.module.scss
  src/components/Alarm/TabCapsule/TabCapsule.tsx
  src/components/test.tsx
  src/hooks/useGoBack.ts
  src/pages/Alarm/Alarm.module.scss
  src/pages/Alarm/Alarm.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/types/alarm.ts
Labels: feat

#37 Feat: mark up trip space page
  src/assets/close.svg
  src/components/BottomSlide/BottomSlide.module.scss
  src/components/BottomSlide/BottomSlide.tsx
  src/components/TripSpace/EditBottomSlideContent/EditBottomSlideContent.module.scss
  src/components/TripSpace/EditBottomSlideContent/EditBottomSlideContent.tsx
  src/hooks/useOnClickOutside.ts
  src/pages/Trip/Trip.module.scss
  src/pages/Trip/Trip.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/types/bottomSlide.ts
Labels: feat

#40 Feat: add list slide
  package-lock.json
  src/components/Home/RecommendedItemList/RecommendedItemList.module.scss
  src/components/Home/RecommendedItemList/RecommendedItemList.tsx
  src/components/Home/RecommendedLocationList/RecommendedLocationList.module.scss
  src/components/Home/RecommendedLocationList/RecommendedLocationList.tsx
  src/components/Home/TabBar/TabBar.tsx
  src/components/Home/TripSpaceAtHome/TripSpaceAtHome.module.scss
  src/components/Home/TripSpaceAtHome/TripSpaceAtHome.tsx
  src/components/Home/TripSpaceAtHome/TripSpaceItem/TripSpaceItem.tsx
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.module.scss
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.tsx
  src/components/Home/VoteAtHome/VoteCard/CardNull/CardNull.module.scss
  src/components/Home/VoteAtHome/VoteCard/CardNull/CardNull.tsx
  src/components/SlideButton/LeftButton/LeftButton.module.scss
  src/components/SlideButton/LeftButton/LeftButton.tsx
  src/components/SlideButton/RightButton/RightButton.module.scss
  src/components/SlideButton/RightButton/RightButton.tsx
  src/components/SlideButton/SlideButton.module.scss
  src/components/SlideButton/SlideButton.tsx
  src/mocks/handlers/home.ts
  src/sass/abstracts/_mixin.scss
  src/types/home.ts
Labels: feat

#45 Feat: create login page
  package-lock.json
  package.json
  src/assets/icons/removeBtn.svg
  src/assets/kakao/kakao_login_large_narrow.png
  src/assets/kakao/kakao_login_large_wide.png
  src/assets/kakao/kakao_login_medium_narrow.png
  src/assets/kakao/kakao_login_medium_wide.png
  src/assets/kakao/kakao_path.svg
  src/assets/logo.svg
  src/components/Auth/Input/Input.module.scss
  src/components/Auth/Input/InputEmail.tsx
  src/components/Auth/Input/InputPassword.tsx
  src/components/Auth/Login/LoginForm.module.scss
  src/components/Auth/Login/LoginForm.tsx
  src/pages/Login/Login.module.scss
  src/pages/Login/Login.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/sass/abstracts/_variables.scss
  src/types/auth.ts
Labels: feat

#44 Fix: remove scrollbar in sidebar #43
  src/components/SideBar/SideBar.tsx
Labels: fix, style

#46 Feat: create main swiper
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/Detail/Contents/Information/Others/Others.module.scss
  src/components/Detail/Contents/Information/Others/Others.tsx
  src/components/Detail/Contents/Information/ShortReveiws/ShortReviews.tsx
  src/components/Detail/Contents/Review/Review.module.scss
  src/components/Detail/Contents/Review/Review.tsx
  src/components/Detail/Contents/Review/ReviewImageSlider/ReviewImageSlider.module.scss
  src/components/Detail/Contents/Review/ReviewImageSlider/ReviewImageSlider.tsx
  src/components/Detail/Contents/Reviews/Reviews.tsx
  src/components/Detail/Main/ImageSwiper/Swiper.module.scss
  src/components/Detail/Main/ImageSwiper/Swiper.tsx
  src/components/Detail/Main/ImageSwiper/SwiperButton/SwiperButton.module.scss
  src/components/Detail/Main/ImageSwiper/SwiperButton/SwiperButton.tsx
  src/components/Detail/Main/ImageSwiper/SwiperIndex/SwiperIndex.module.scss
  src/components/Detail/Main/ImageSwiper/SwiperIndex/SwiperIndex.tsx
  src/components/Detail/Main/Main.tsx
  src/components/Detail/Main/Swiper/Swiper.module.scss
  src/components/Detail/Main/Swiper/Swiper.tsx
  src/pages/Detail/Detail.tsx
  src/types/detail.ts
Labels: feat

#47 Feat: create friend list, invite friend bottom sheet #42
  package-lock.json
  src/assets/InviteLogo.svg
  src/assets/inviteKakao.svg
  src/assets/inviteLink.svg
  src/components/Modal/CopyClipboard/CopyClipboad.module.scss
  src/components/Modal/CopyClipboard/CopyClipboard.tsx
  src/components/TripSpace/FriendList/FriendList.module.scss
  src/components/TripSpace/FriendList/FriendList.tsx
  src/components/TripSpace/InviteFriends/InviteFriends.module.scss
  src/components/TripSpace/InviteFriends/InviteFriends.tsx
  src/pages/Trip/Trip.tsx
  src/sass/abstracts/_variables.scss
  src/types/FriendList.ts
Labels: feat

#51 Fix: remove friend list scroll bar #50
  .env
  src/components/TripSpace/FriendList/FriendList.module.scss
Labels: fix

#58 Feat: create search page
  src/components/Detail/Main/Swiper/Swiper.module.scss
  src/components/Detail/Main/Swiper/Swiper.tsx
  src/components/Home/RecommendedItemList/RecommendedItem/RecommendedItem.tsx
  src/components/Home/SearchBarAtHome/SearchBarAtHome.tsx
  src/components/Home/TabBar/TabBar.tsx
  src/components/Review/Review.module.scss
  src/components/Review/Review.tsx
  src/components/Review/ReviewImageSlider/ReviewImageSlider.module.scss
  src/components/Review/ReviewImageSlider/ReviewImageSlider.tsx
  src/components/SearchFromHome/SearchBar/SearchBar.module.scss
  src/components/SearchFromHome/SearchBar/SearchBar.tsx
  src/components/SearchFromHome/SearchHome/HotItems/HotItem/HotItem.module.scss
  src/components/SearchFromHome/SearchHome/HotItems/HotItem/HotItem.tsx
  src/components/SearchFromHome/SearchHome/HotItems/HotItems.module.scss
  src/components/SearchFromHome/SearchHome/HotItems/HotItems.tsx
  src/components/SearchFromHome/SearchHome/SearchHome.module.scss
  src/components/SearchFromHome/SearchHome/SearchHome.tsx
  src/components/SearchFromHome/SearchHome/SearchKeyword/SearchKeyword.module.scss
  src/components/SearchFromHome/SearchHome/SearchKeyword/SearchKeyword.tsx
  src/components/SearchFromHome/SearchList/DateFilter/DateFilter.module.scss
  src/components/SearchFromHome/SearchList/DateFilter/DateFilter.tsx
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFilter.module.scss
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFilter.tsx
  src/components/SearchFromHome/SearchList/MapButton/MapButton.module.scss
  src/components/SearchFromHome/SearchList/MapButton/MapButton.tsx
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.module.scss
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.tsx
  src/components/SearchFromHome/SearchList/SearchList.module.scss
  src/components/SearchFromHome/SearchList/SearchList.tsx
  src/components/SearchFromHome/SearchList/Tabs/Tab/Tab.module.scss
  src/components/SearchFromHome/SearchList/Tabs/Tab/Tab.tsx
  src/components/SearchFromHome/SearchList/Tabs/Tabs.module.scss
  src/components/SearchFromHome/SearchList/Tabs/Tabs.tsx
  src/components/SlideButton/LeftButton/LeftButton.tsx
  src/components/SlideButton/RightButton/RightButton.tsx
  src/components/SlideButton/SlideButton.module.scss
  src/components/SlideButton/SlideButton.tsx
  src/components/Vote/VoteCandidateItem/VoteCandidateItem.module.scss
  src/components/Vote/VoteCandidateItem/VoteCandidateItem.tsx
  src/components/Vote/VoteDetailsBottomButton/VoteDetailsBottomButton.module.scss
  src/components/Vote/VoteDetailsBottomButton/VoteDetailsBottomButton.tsx
  src/components/Vote/VoteDetailsField/VoteDetailsField.module.scss
  src/components/Vote/VoteDetailsField/VoteDetailsField.tsx
  src/components/Vote/VoteDetailsFieldZero/VoteDetailsFieldZero.module.scss
  src/components/Vote/VoteDetailsFieldZero/VoteDetailsFieldZero.tsx
  src/components/Vote/VoteDetailsHeader/VoteDetailsHeader.module.scss
  src/components/Vote/VoteDetailsHeader/VoteDetailsHeader.tsx
  src/mocks/handlers/home.ts
  src/pages/SearchFromHome/SearchFromHome.module.scss
  src/pages/SearchFromHome/SearchFromHome.tsx
  src/pages/Trip/Trip.tsx
  src/pages/VoteDetail/VoteDetail.module.scss
  src/pages/VoteDetail/VoteDetail.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/types/home.ts
Labels: feat

#61 Feat: markup vote tab in trip space #55
  src/assets/ic_vote.svg
  src/assets/voteIcons/avatar_smile.svg
  src/assets/voteIcons/ic_vote.svg
  src/assets/voteIcons/swiper-next-btn.svg
  src/assets/voteIcons/swiper-prev-btn.svg
  src/assets/voteIcons/vote_card_check.svg
  src/assets/voteIcons/vote_check.svg
  src/assets/voteIcons/vote_edit.svg
  src/assets/voteIcons/vote_heart.svg
  src/assets/voteIcons/vote_repeat.svg
  src/assets/voteIcons/vote_search.svg
  src/assets/voteIcons/vote_trash.svg
  src/chakra/avatarCustom.ts
  src/chakra/chakraCustomTheme.ts
  src/chakra/tabsCustom.ts
  src/components/BottomSlide/BottomSlide.module.scss
  src/components/BottomSlide/BottomSlide.tsx
  src/components/Detail/Main/Swiper/Swiper.module.scss
  src/components/Detail/Main/Swiper/Swiper.tsx
  src/components/Review/Review.module.scss
  src/components/Review/Review.tsx
  src/components/Review/ReviewImageSlider/ReviewImageSlider.module.scss
  src/components/Review/ReviewImageSlider/ReviewImageSlider.tsx
  src/components/Vote/CreatVoteTitleModal/CreatVoteTitleModal.tsx
  src/components/Vote/VoteBottomSlideContent/AddCandidate/AddCandidate.tsx
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/VoteMeatball.tsx
  src/components/Vote/VoteCandidateItem/VoteCandidateItem.module.scss
  src/components/Vote/VoteCandidateItem/VoteCandidateItem.tsx
  src/components/Vote/VoteDetailsBottomButton/VoteDetailsBottomButton.module.scss
  src/components/Vote/VoteDetailsBottomButton/VoteDetailsBottomButton.tsx
  src/components/Vote/VoteDetailsField/VoteDetailsField.module.scss
  src/components/Vote/VoteDetailsField/VoteDetailsField.tsx
  src/components/Vote/VoteDetailsFieldZero/VoteDetailsFieldZero.module.scss
  src/components/Vote/VoteDetailsFieldZero/VoteDetailsFieldZero.tsx
  src/components/Vote/VoteDetailsHeader/VoteDetailsHeader.module.scss
  src/components/Vote/VoteDetailsHeader/VoteDetailsHeader.tsx
  src/components/VoteTabPanel/TabsVoteCard/TabsVoteCard.module.scss
  src/components/VoteTabPanel/TabsVoteCard/TabsVoteCard.tsx
  src/components/VoteTabPanel/VoteTabPanel.module.scss
  src/components/VoteTabPanel/VoteTabPanel.tsx
  src/main.tsx
  src/mocks/handlers/index.ts
  src/mocks/handlers/vote.ts
  src/pages/Trip/Trip.module.scss
  src/pages/Trip/Trip.tsx
  src/pages/VoteDetail/VoteDetail.module.scss
  src/pages/VoteDetail/VoteDetail.tsx
Labels: feat, fix, design

#64 Fix: redesign sidebar #57
  src/assets/plus.svg
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/SideBar.tsx
  src/components/SideBar/TravelList/TravelList.module.scss
  src/components/SideBar/TravelList/TravelList.tsx
  src/pages/Trip/Trip.tsx
  src/types/sidebar.ts
Labels: feat, fix, design

#63 Feat: create calendar modal
  package-lock.json
  package.json
  src/assets/back.svg
  src/chakra/chakraCustomTheme.ts
  src/components/TripSpace/CalendarModal/CalendarModal.module.scss
  src/components/TripSpace/CalendarModal/CalendarModal.tsx
  src/utils/printDayNight.ts
Labels: feat

#67 Feat: create home onboarding modal
  public/onboardingBag.png
  src/components/Home/Onboarding/Icons.tsx
  src/components/Home/Onboarding/Onboarding.module.scss
  src/components/Home/Onboarding/Onboarding.tsx
  src/pages/Home/Home.tsx
Labels: feat

#69 Feat: create invitation modal #65
  src/components/Modal/Invitation/Invitation.module.scss
  src/components/Modal/Invitation/Invitation.tsx
  src/hooks/useLockBodyScroll.ts
  src/types/Invitation.ts
Labels: feat

#75 #70 feat create before days function
  src/components/Alarm/TabCapsule/Content/Content.module.scss
  src/components/Alarm/TabCapsule/Content/Content.tsx
  src/components/Alarm/TabCapsule/TabCapsule.tsx
  src/utils/formatTimeAgo.ts
  src/utils/test.ts
Labels: feat

#71 Feat: create pages about email signup #20
  src/assets/icons/InputRemove.svg
  src/assets/icons/camera.svg
  src/assets/icons/checkbox.svg
  src/assets/icons/checkbox_checked.svg
  src/assets/profile_default.svg
  src/components/Auth/Button/AuthButton.module.scss
  src/components/Auth/Button/AuthButton.tsx
  src/components/Auth/Login/Input/Input.module.scss
  src/components/Auth/Login/Input/InputEmail.tsx
  src/components/Auth/Login/Input/InputPassword.tsx
  src/components/Auth/Login/LoginForm.module.scss
  src/components/Auth/Login/LoginForm.tsx
  src/components/Auth/Signup/AgreeForm.module.scss
  src/components/Auth/Signup/AgreeForm.tsx
  src/components/Auth/Signup/Header/Header.module.scss
  src/components/Auth/Signup/Header/Header.tsx
  src/components/Auth/Signup/SignupForm.module.scss
  src/components/Auth/Signup/SignupForm.tsx
  src/components/Auth/Signup/Step/Step.module.scss
  src/components/Auth/Signup/Step/StepEmail.tsx
  src/components/Auth/Signup/Step/StepEmailSert.tsx
  src/components/Auth/Signup/Step/StepPassword.tsx
  src/components/Auth/Signup/Step/StepProfile.tsx
  src/pages/Login/Login.tsx
  src/pages/Signup/Agree/AgreePrivacy.tsx
  src/pages/Signup/Agree/AgreeService.tsx
  src/pages/Signup/Signup.module.scss
  src/pages/Signup/Signup.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/types/auth.ts
  src/utils/inputValidation.ts
Labels: feat

#82 Update README.md
  README.md
Labels: docs

#86 Feat: add branching logic space creation button #85
  src/components/SideBar/TravelList/TravelList.tsx
Labels: feat

#87 Feat: create region select page
  src/chakra/chakraCustomTheme.ts
  src/chakra/tagCustom.ts
  src/components/TripSpace/CalendarModal/CalendarModal.module.scss
  src/components/TripSpace/CalendarModal/CalendarModal.tsx
  src/components/TripSpace/NoSearchResult/NoSearchResult.module.scss
  src/components/TripSpace/NoSearchResult/NoSearchResult.tsx
  src/components/TripSpace/RegionList/RegionList.module.scss
  src/components/TripSpace/RegionList/RegionList.tsx
  src/components/TripSpace/RegionSearchBox/RegionSearchBox.module.scss
  src/components/TripSpace/RegionSearchBox/RegionSearchBox.tsx
  src/components/TripSpace/RegionTagItem/RegionTagItem.tsx
  src/components/TripSpace/SelectHeader/SelectHeader.module.scss
  src/components/TripSpace/SelectHeader/SelectHeader.tsx
  src/pages/RegionSearch/RegionSearch.module.scss
  src/pages/RegionSearch/RegionSearch.tsx
  src/types/regionSearch.ts
  src/types/selectHeader.ts
Labels: feat, design

#84 Design: apply design modification #80
  src/components/SideBar/SideBar.module.scss
  src/pages/Trip/Trip.tsx
Labels: design

#96 Feat: search page add map api
  index.html
  src/assets/homeIcons/home/closeButton.svg
  src/assets/homeIcons/home/fireIcon.svg
  src/assets/homeIcons/home/rank1.svg
  src/assets/homeIcons/home/rank2.svg
  src/assets/homeIcons/home/snowIcon.svg
  src/assets/homeIcons/map/flag.svg
  src/assets/homeIcons/map/flag_big.svg
  src/assets/homeIcons/map/house.svg
  src/assets/homeIcons/map/house_big.svg
  src/assets/homeIcons/map/restaurant.svg
  src/assets/homeIcons/map/restaurant_big.svg
  src/components/Home/Onboarding/Onboarding.tsx
  src/components/Home/TripSpaceAtHome/TripSpaceItem/TripSpaceItem.tsx
  src/components/SearchFromHome/SearchList/Map/Map.module.scss
  src/components/SearchFromHome/SearchList/Map/Map.tsx
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItem/MapItem.tsx
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItems.tsx
  src/components/SearchFromHome/SearchList/MapButton/MapButton.tsx
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.tsx
  src/components/SearchFromHome/SearchList/Tabs/Tab/Tab.tsx
  src/components/SlideButton/SlideButton.tsx
  src/kakao.d.ts
  src/mocks/handlers/home.ts
  src/types/home.ts
Labels: feat

#92 Feat: complete trip space page
  src/chakra/chakraCustomTheme.ts
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/TripSpace/EditBottomSlideContent/EditBottomSlideContent.tsx
  src/components/TripSpace/EditTripSpace/EditTripSpace.module.scss
  src/components/TripSpace/EditTripSpace/EditTripSpace.tsx
  src/components/TripSpace/LeaveTripModal/LeaveTripModal.tsx
  src/components/TripSpace/SelectHeader/SelectHeader.module.scss
  src/components/TripSpace/SelectHeader/SelectHeader.tsx
  src/pages/Calendar/Calendar.module.scss
  src/pages/Calendar/Calendar.tsx
  src/pages/RegionSearch/RegionSearch.module.scss
  src/pages/RegionSearch/RegionSearch.tsx
  src/pages/Trip/Trip.module.scss
  src/pages/Trip/Trip.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/types/modal.ts
Labels: feat

#94 Design: redesign vote page and create common modal #60
  src/assets/voteIcons/rank_1.svg
  src/assets/voteIcons/rank_2.svg
  src/assets/voteIcons/rank_3.svg
  src/assets/voteIcons/vote_addDay.svg
  src/chakra/chakraCustomTheme.ts
  src/chakra/modalCustom.ts
  src/components/AlertModal/AlertModal.module.scss
  src/components/AlertModal/AlertModal.tsx
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/VoteMeatball.tsx
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/modalContent.ts
  src/components/Vote/VoteBottomSlideContent/VotedUserList/VotedUserList.module.scss
  src/components/Vote/VoteBottomSlideContent/VotedUserList/VotedUserList.tsx
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.module.scss
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.tsx
  src/components/Vote/VoteContent/VoteContent.module.scss
  src/components/Vote/VoteContent/VoteContent.tsx
  src/components/Vote/VoteContent/VoteContentEmpty/VoteContentEmpty.module.scss
  src/components/Vote/VoteContent/VoteContentEmpty/VoteContentEmpty.tsx
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendItem/VoteRecommendItem.module.scss
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendItem/VoteRecommendItem.tsx
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendList.tsx
  src/components/Vote/VoteHeader/VoteHeader.module.scss
  src/components/Vote/VoteHeader/VoteHeader.tsx
  src/components/VoteTabPanel/TabsVoteCard/TabsVoteCard.module.scss
  src/components/VoteTabPanel/TabsVoteCard/TabsVoteCard.tsx
  src/components/VoteTabPanel/VoteTabPanel.module.scss
  src/components/VoteTabPanel/VoteTabPanel.tsx
  src/components/VoteTabPanel/VoteTabPanelEmpty/VoteTabPanelEmpty.module.scss
  src/components/VoteTabPanel/VoteTabPanelEmpty/VoteTabPanelEmpty.tsx
  src/mocks/handlers/vote.ts
  src/pages/Vote/Vote.tsx
  src/recoil/vote/alertModal.ts
  src/recoil/vote/bottomSlide.ts
  src/routes/MainRouter/MainRouter.tsx
  src/types/vote.ts
Labels: feat, design

#98 56 feat create detail page markup 2
  package-lock.json
  public/mockServiceWorker.js
  src/components/Detail/BottomFixedBtn/BottomFixedBtn.module.scss
  src/components/Detail/BottomFixedBtn/BottomFixedBtn.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationListItem/RegistrationListItem.module.scss
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationListItem/RegistrationListItem.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationSlide.module.scss
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationSlide.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationTripSpace/RegistrationTripSpace.module.scss
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationTripSpace/RegistrationTripSpace.tsx
  src/components/Detail/BottomSlideDetail/BottomSlideDetail.module.scss
  src/components/Detail/BottomSlideDetail/BottomSlideDetail.tsx
  src/components/Detail/Contents/Contents.tsx
  src/components/Detail/Contents/Information/Information.tsx
  src/components/Detail/Contents/Information/Others/OtherCard/OtherCard.module.scss
  src/components/Detail/Contents/Information/Others/Others.module.scss
  src/components/Detail/Contents/Information/Others/Others.tsx
  src/components/Detail/Contents/Information/ShortReveiws/ShortReviews.tsx
  src/components/Detail/Contents/Review/Review.module.scss
  src/components/Detail/Contents/Review/ReviewImageSlider/ReviewImageSlider.module.scss
  src/components/Detail/Contents/Review/ReviewImageSlider/ReviewImageSlider.tsx
  src/components/Detail/Contents/ReviewBottomSlide/DateWrapper/DateWrapper.module.scss
  src/components/Detail/Contents/ReviewBottomSlide/DateWrapper/DateWrapper.tsx
  src/components/Detail/Contents/ReviewBottomSlide/ImagesWrapper/ImagesWrapper.module.scss
  src/components/Detail/Contents/ReviewBottomSlide/ImagesWrapper/ImagesWrapper.tsx
  src/components/Detail/Contents/ReviewBottomSlide/InputWrapper/InputWrapper.module.scss
  src/components/Detail/Contents/ReviewBottomSlide/InputWrapper/InputWrapper.tsx
  src/components/Detail/Contents/ReviewBottomSlide/ReviewBottomSlide.module.scss
  src/components/Detail/Contents/ReviewBottomSlide/ReviewBottomSlide.tsx
  src/components/Detail/Contents/ReviewBottomSlide/StarsWrapper/StarsWrapper.module.scss
  src/components/Detail/Contents/ReviewBottomSlide/StarsWrapper/StarsWrapper.tsx
  src/components/Detail/Contents/Reviews/Reviews.tsx
  src/components/Detail/Main/Title/Title.tsx
  src/components/Detail/Navigation/MeatballBottomSlide/MeatballBottomSlide.module.scss
  src/components/Detail/Navigation/MeatballBottomSlide/MeatballBottomSlide.tsx
  src/components/Detail/Navigation/Navigation.tsx
  src/components/SlideButton/SlideButton.tsx
  src/components/useToastCustom/useToastCustom.module.scss
  src/components/useToastCustom/useToastCustom.tsx
  src/pages/Detail/Detail.tsx
  src/recoil/detail/detail.ts
  src/routes/MainRouter/MainRouter.tsx
  src/sass/base/_normalize.scss
  src/types/bottomSlide.ts
  src/types/detail.ts
  src/types/interface.ts
  src/types/test.ts
Labels: feat

#101 Hotfix: change usetoastcustom name
  src/components/CustomToast/CustomToast.module.scss
  src/components/CustomToast/CustomToast.tsx
  src/components/Detail/Navigation/MeatballBottomSlide/MeatballBottomSlide.tsx
Labels: hotfix

#103 Feat: create detail page map
  package-lock.json
  package.json
  src/components/Detail/Contents/Information/BasicInformation/BasicInformation.tsx
  src/components/Detail/Contents/Information/BasicInformation/Map/Map.tsx
  src/components/Detail/Contents/Information/BasicInformation/MapInDetail/MapInDetail.module.scss
  src/components/Detail/Contents/Information/BasicInformation/MapInDetail/MapInDetail.tsx
Labels: feat

#108 Refactor: search keyword method change
  src/components/Home/Onboarding/Onboarding.module.scss
  src/components/SearchFromHome/MapHeader/MapHeader.module.scss
  src/components/SearchFromHome/MapHeader/MapHeader.tsx
  src/components/SearchFromHome/SearchBar/SearchBar.module.scss
  src/components/SearchFromHome/SearchBar/SearchBar.tsx
  src/components/SearchFromHome/SearchHome/SearchHome.module.scss
  src/components/SearchFromHome/SearchHome/SearchKeyword/SearchKeyword.tsx
  src/components/SearchFromHome/SearchList/Map/Map.tsx
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItem/MapItem.tsx
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItems.tsx
  src/components/SearchFromHome/SearchList/SearchList.module.scss
  src/components/SearchFromHome/SearchList/SearchList.tsx
  src/components/SearchFromHome/SearchList/Tabs/Tab/Tab.tsx
  src/components/SearchFromHome/SearchList/Tabs/Tabs.tsx
  src/pages/SearchFromHome/SearchFromHome.module.scss
  src/pages/SearchFromHome/SearchFromHome.tsx
Labels: refactor

#110 Feat: create route tab component
  src/assets/tripIcons/marker1.svg
  src/assets/tripIcons/marker2.svg
  src/assets/tripIcons/marker3.svg
  src/components/Route/DayNavigationBar/DayNavigationBar.module.scss
  src/components/Route/DayNavigationBar/DayNavigationBar.tsx
  src/components/Route/DayRoute/DayRoute.module.scss
  src/components/Route/DayRoute/DayRoute.tsx
  src/components/Route/EmptyDate/EmptyDate.module.scss
  src/components/Route/EmptyDate/EmptyDate.tsx
  src/components/Route/EmptyRoute/EmptyRoute.module.scss
  src/components/Route/EmptyRoute/EmptyRoute.tsx
  src/components/Route/MapInTrip/MapInTrip.module.scss
  src/components/Route/MapInTrip/MapInTrip.tsx
  src/components/Route/PlaceCard/PlaceCard.module.scss
  src/components/Route/PlaceCard/PlaceCard.tsx
  src/components/Route/RouteTabPanel/RouteTabPanel.module.scss
  src/components/Route/RouteTabPanel/RouteTabPanel.tsx
  src/pages/Trip/Trip.tsx
  src/types/route.ts
Labels: feat

#113 Feat: create modal and edit bottom slide
  src/chakra/modalCustom.ts
  src/components/CustomToast/CustomToast.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationListItem/RegistrationListItem.module.scss
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationListItem/RegistrationListItem.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationModal/RegistrationModal.module.scss
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationModal/RegistrationModal.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationSlide.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationTripSpace/RegistrationTripSpace.tsx
  src/components/Detail/BottomSlideDetail/BottomSlideDetail.tsx
  src/components/Detail/Contents/Review/ReviewImageSlider/ReviewImageSlider.tsx
  src/components/Detail/Contents/ReviewBottomSlide/InputWrapper/InputWrapper.module.scss
  src/components/Detail/Navigation/MeatballBottomSlide/MeatballBottomSlide.tsx
  src/pages/Detail/Detail.tsx
  src/types/detail.ts
Labels: feat

#112 Hotfix: modify alert modal state to recoil and fix the modal style
  src/assets/voteIcons/checkbox_checked.svg
  src/chakra/buttonCustom.ts
  src/chakra/chakraCustomTheme.ts
  src/chakra/checkboxCustom.ts
  src/chakra/modalCustom.ts
  src/components/AlertModal/AlertModal.tsx
  src/components/Vote/CreatVoteTitleModal/CreatVoteTitleModal.tsx
  src/components/Vote/DeleteCandidatesButton/DeleteCandidatesButton.module.scss
  src/components/Vote/DeleteCandidatesButton/DeleteCandidatesButton.tsx
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/VoteMeatball.module.scss
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/VoteMeatball.tsx
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.tsx
  src/components/Vote/VoteContent/CandidateList/CandidateList.module.scss
  src/components/Vote/VoteContent/CandidateList/CandidateList.tsx
  src/components/Vote/VoteContent/VoteContent.module.scss
  src/components/Vote/VoteContent/VoteContent.tsx
  src/mocks/handlers/vote.ts
  src/pages/Vote/Vote.tsx
  src/recoil/vote/alertModal.ts
  src/recoil/vote/candidateList.ts
  src/types/vote.ts
Labels: feat, design, hotfix

#123 Feat: connect API #97
  package-lock.json
  package.json
  src/App.tsx
  src/api/axiosInstance.ts
  src/components/Alarm/Alarm.module.scss
  src/components/Alarm/Alarm.tsx
  src/components/Alarm/Back/Back.tsx
  src/components/Alarm/TabCapsule/TabCapsule.tsx
  src/components/Modal/CopyClipboard/CopyClipboad.module.scss
  src/components/Modal/Invitation/Invitation.module.scss
  src/components/Modal/Invitation/Invitation.tsx
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/SideBar.tsx
  src/components/SideBar/TravelList/TravelList.tsx
  src/components/TripSpace/FriendList/FriendList.tsx
  src/components/TripSpace/InviteFriends/InviteFriends.tsx
  src/hooks/Invite/useInviteCode.ts
  src/hooks/Spaces/useSpaces.ts
  src/hooks/User/useUser.ts
  src/hooks/useKakaoShareButton.ts
  src/mocks/handlers/Invite.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/sidebar.ts
  src/pages/Alarm/Alarm.module.scss
  src/pages/Alarm/Alarm.tsx
  src/pages/Home/Home.tsx
  src/pages/Trip/Trip.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/types/Invitation.ts
  src/types/alarm.ts
  src/types/inviteFriends.ts
  src/types/sidebar.ts
  src/utils/parseInviteCode.ts
Labels: feat

#126 111 feat create add places from vote component
  src/components/BottomSlide/BottomSlide.module.scss
  src/components/Route/AddPlace/AddPlace.module.scss
  src/components/Route/AddPlace/AddPlace.tsx
  src/components/Route/AddPlace/FromVote/CompletedVote/CompletedVote.module.scss
  src/components/Route/AddPlace/FromVote/CompletedVote/CompletedVote.tsx
  src/components/Route/AddPlace/FromVote/InProgressVote/InProgressVote.module.scss
  src/components/Route/AddPlace/FromVote/InProgressVote/InProgressVote.tsx
  src/components/Route/AddPlace/FromVote/PlaceList/PlaceList.module.scss
  src/components/Route/AddPlace/FromVote/PlaceList/PlaceList.tsx
  src/components/Route/AddPlace/FromVote/VoteCard/VoteCard.module.scss
  src/components/Route/AddPlace/FromVote/VoteCard/VoteCard.tsx
  src/components/Route/DayRoute/DayRoute.module.scss
  src/components/Route/DayRoute/DayRoute.tsx
  src/components/Route/RouteTabPanel/RouteTabPanel.module.scss
  src/pages/AddPlaceFromVote/AddPlaceFromVote.module.scss
  src/pages/AddPlaceFromVote/AddPlaceFromVote.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/types/route.ts
Labels: feat

#125 Refactor: change home search api endpoint
  public/homeFireIcon.png
  public/homeMusicIcon.png
  public/homeSnowmanIcon.png
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/Home/Onboarding/Onboarding.module.scss
  src/components/Home/Onboarding/Onboarding.tsx
  src/components/Home/RecommendedItemList/RecommendedItem/RecommendedItem.tsx
  src/components/Home/RecommendedLocationList/RecommendedLocation/RecommendedLocation.tsx
  src/components/Home/VoteAtHome/VoteCard/CardNull/CardNull.tsx
  src/components/SearchFromHome/SearchHome/HotItems/HotItem/HotItem.tsx
  src/components/SearchFromHome/SearchHome/HotItems/HotItems.tsx
  src/components/SearchFromHome/SearchHome/SearchHome.tsx
  src/components/SearchFromHome/SearchList/Map/Map.module.scss
  src/components/SearchFromHome/SearchList/Map/Map.tsx
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItem/MapItem.tsx
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItems.tsx
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.tsx
  src/components/SearchFromHome/SearchList/SearchList.tsx
  src/mocks/handlers/home.ts
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
  src/pages/SearchFromHome/SearchFromHome.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/types/home.ts
  src/utils/areas.json
Labels: feat, refactor

#132 Fix: fix kakao map
  src/assets/tripIcons/marker1.svg
  src/assets/tripIcons/marker2.svg
  src/assets/tripIcons/marker3.svg
  src/components/Route/DayNavigationBar/DayNavigationBar.module.scss
  src/components/Route/MapInTrip/MapInTrip.module.scss
  src/components/Route/MapInTrip/MapInTrip.tsx
  src/components/Route/RouteTabPanel/RouteTabPanel.tsx
  src/components/TripSpace/SelectHeader/SelectHeader.module.scss
  src/components/TripSpace/SelectHeader/SelectHeader.tsx
  src/pages/Trip/Trip.tsx
  src/types/route.ts
Labels: fix, design

#136 Feat: search location filter markup
  src/assets/homeIcons/home/fireImoji.svg
  src/assets/homeIcons/home/musicImoji.svg
  src/assets/homeIcons/home/snowmanImoji.svg
  src/assets/homeIcons/search/check.svg
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.tsx
  src/components/Home/VoteAtHome/VoteCard/CardNull/CardNull.tsx
  src/components/SearchFromHome/SearchList/DateFilter/DateFilter.tsx
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFilter.module.scss
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFilter.tsx
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/LocationFliterPage.module.scss
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/LocationFliterPage.tsx
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/PopularList/PopularList.module.scss
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/PopularList/PopularList.tsx
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/SelectLocation/SelectLocation.module.scss
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/SelectLocation/SelectLocation.tsx
  src/components/SearchFromHome/SearchList/Map/Map.tsx
  src/components/SearchFromHome/SearchList/SearchList.module.scss
  src/components/SearchFromHome/SearchList/SearchList.tsx
  src/mocks/handlers/home.ts
  src/pages/Home/Home.tsx
  src/utils/areas.json
Labels: feat

#143 Hotfix: remove nav global style
  src/components/Route/DayNavigationBar/DayNavigationBar.module.scss
  src/components/Route/DayNavigationBar/DayNavigationBar.tsx
  src/pages/AddPlaceFromVote/AddPlaceFromVote.module.scss
  src/pages/AddPlaceFromVote/AddPlaceFromVote.tsx
Labels: design, hotfix

#144 Feat: create search and wish page's button in vote and add react-query
  src/App.tsx
  src/api/vote.ts
  src/components/ButtonsInAddingCandidate/AddToCandidateButton/AddToCandidateButton.tsx
  src/components/ButtonsInAddingCandidate/SelectButton/SelectButton.module.scss
  src/components/ButtonsInAddingCandidate/SelectButton/SelectButton.tsx
  src/components/Vote/CreatVoteTitleModal/CreatVoteTitleModal.module.scss
  src/components/Vote/CreatVoteTitleModal/CreatVoteTitleModal.tsx
  src/components/Vote/CreateVoteModal/CreateVoteModal.tsx
  src/components/Vote/CreateVoteModal/CreateVoteModalButton.tsx
  src/components/Vote/DeleteCandidatesButton/DeleteCandidatesButton.tsx
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/VoteMeatball.tsx
  src/components/VoteMemo/MemoContent.tsx
  src/components/VoteTabPanel/VoteTabPanel.tsx
  src/hooks/Votes/vote.ts
  src/mocks/handlers/vote.ts
  src/mocks/jest/postNewVote.test.ts
  src/pages/CandidatesMap/CandidatesMap.tsx
  src/pages/Vote/Vote.tsx
  src/pages/Vote/VoteMemo/VoteMemo.tsx
  src/recoil/vote/createVoteTitleModal.ts
  src/types/vote.ts
Labels: feat

#147 Feat: create home recommend data
  src/api/search.ts
  src/components/Home/RecommendedItemList/RecommendedItem/RecommendedItem.tsx
  src/components/Home/RecommendedItemList/RecommendedItemList.tsx
  src/components/Home/RecommendedLocationList/RecommendedLocation/RecommendedLocation.tsx
  src/components/Home/RecommendedLocationList/RecommendedLocationList.tsx
  src/components/Home/TripSpaceAtHome/TripSpaceAtHome.tsx
  src/components/Home/TripSpaceAtHome/TripSpaceItem/TripSpaceItem.tsx
  src/components/Home/VoteAtHome/VoteAtHome.tsx
  src/components/SearchFromHome/MapHeader/MapHeader.tsx
  src/components/SearchFromHome/SearchBar/SearchBar.tsx
  src/components/SearchFromHome/SearchHome/HotItems/HotItems.tsx
  src/components/SearchFromHome/SearchHome/SearchHome.tsx
  src/components/SearchFromHome/SearchHome/SearchKeyword/SearchKeyword.tsx
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFilter.module.scss
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFilter.tsx
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/LocationFliterPage.module.scss
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/LocationFliterPage.tsx
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/PopularList/PopularList.module.scss
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/PopularList/PopularList.tsx
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/SelectLocation/SelectLocation.module.scss
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/SelectLocation/SelectLocation.tsx
  src/components/SearchFromHome/SearchList/Map/Map.tsx
  src/components/SearchFromHome/SearchList/SearchList.tsx
  src/components/SearchFromHome/SearchList/Tabs/Tab/Tab.tsx
  src/components/SearchFromHome/SearchList/Tabs/Tabs.tsx
  src/hooks/Search/useSearch.ts
  src/mocks/handlers/home.ts
  src/pages/Home/Home.tsx
  src/pages/SearchFromHome/SearchFromHome.module.scss
  src/pages/SearchFromHome/SearchFromHome.tsx
  src/types/home.ts
  src/utils/areas.json
  src/utils/categories.json
  src/utils/contentType.json
Labels: feat

#146 Feat: detail page last markup
  src/chakra/modalCustom.ts
  src/components/Detail/BottomFixedBtn/BottomFixedBtn.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationModal/RegistrationModal.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationSlide.module.scss
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationSlide.tsx
  src/components/Detail/BottomSlideDetail/BottomSlideDetail.tsx
  src/components/Detail/Contents/Contents.tsx
  src/components/Detail/Contents/Information/BasicInformation/BasicInformation.tsx
  src/components/Detail/Contents/Information/BasicInformation/MapInDetail/MapInDetail.tsx
  src/components/Detail/Contents/Information/BasicInformation/MapModal/MapModal.module.scss
  src/components/Detail/Contents/Information/BasicInformation/MapModal/MapModal.tsx
  src/components/Detail/Contents/Information/Others/OtherCard/OtherCard.module.scss
  src/components/Detail/Contents/Information/Others/OtherCard/OtherCard.tsx
  src/components/Detail/Contents/Information/Others/Others.tsx
  src/components/Detail/Contents/Information/ShortReveiws/ShortReviews.tsx
  src/components/Detail/Contents/Review/ReviewImageSlider/ReviewImageSlider.tsx
  src/components/Detail/Contents/ReviewBottomSlide/ReviewBottomSlide.tsx
  src/components/Detail/Contents/Reviews/Reviews.module.scss
  src/components/Detail/Contents/Reviews/Reviews.tsx
  src/components/Detail/Main/ImageSwiper/Swiper.tsx
  src/components/Detail/Main/ImageSwiper/SwiperButton/SwiperButton.tsx
  src/components/Detail/Main/ImageSwiper/SwiperIndex/SwiperIndex.tsx
  src/components/Detail/Main/SlideModal/SlideModal.module.scss
  src/components/Detail/Main/SlideModal/SlideModal.tsx
  src/components/Detail/Main/Title/Title.tsx
  src/components/Detail/Navigation/MeatballBottomSlide/MeatballBottomSlide.tsx
  src/pages/Detail/Detail.tsx
  src/recoil/detail/detail.ts
  src/types/detail.ts
Labels: feat

#154 Fix: change search api
  src/assets/homeIcons/search/nullImg.svg
  src/components/Home/Onboarding/Onboarding.module.scss
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.module.scss
  src/components/Home/VoteAtHome/VoteCard/CardNull/CardNull.module.scss
  src/components/SearchFromHome/SearchBar/SearchBar.tsx
  src/components/SearchFromHome/SearchHome/HotItems/HotItem/HotItem.module.scss
  src/components/SearchFromHome/SearchHome/HotItems/HotItem/HotItem.tsx
  src/components/SearchFromHome/SearchHome/HotItems/HotItems.tsx
  src/components/SearchFromHome/SearchHome/SearchHome.tsx
  src/components/SearchFromHome/SearchHome/SearchKeyword/SearchKeyword.tsx
  src/components/SearchFromHome/SearchList/DateFilter/DateFilter.module.scss
  src/components/SearchFromHome/SearchList/DateFilter/DateFilter.tsx
  src/components/SearchFromHome/SearchList/LocationFilter/LocationFliterPage/LocationFliterPage.tsx
  src/components/SearchFromHome/SearchList/Map/Map.tsx
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItem/MapItem.tsx
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItems.tsx
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.module.scss
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.tsx
  src/components/SearchFromHome/SearchList/SearchList.module.scss
  src/components/SearchFromHome/SearchList/SearchList.tsx
  src/components/SearchFromHome/SearchList/Tabs/Tab/Tab.tsx
  src/hooks/Search/useSearch.ts
  src/mocks/handlers/home.ts
  src/pages/Home/Home.tsx
  src/pages/SearchFromHome/SearchFromHome.tsx
  src/types/home.ts
  src/utils/titleCaseChange.ts
Labels: fix

#155 Feat: add edit mode in route tab
  package-lock.json
  package.json
  src/App.tsx
  src/components/BottomSlide/BottomSlide.module.scss
  src/components/BottomSlide/BottomSlideLeft.tsx
  src/components/MapZoomIn/RouteMapSlide/RouteMapSlide.tsx
  src/components/Route/DayMove/DayMove.module.scss
  src/components/Route/DayMove/DayMove.tsx
  src/components/Route/DayNavigationBar/DayNavigationBar.module.scss
  src/components/Route/DayNavigationBar/DayNavigationBar.tsx
  src/components/Route/DayRoute/DayRoute.tsx
  src/components/Route/DraggablePlaceCard/DraggablePlaceCard.tsx
  src/components/Route/PlaceCard/PlaceCard.module.scss
  src/components/Route/PlaceCard/PlaceCard.tsx
  src/components/Route/RouteTabPanel/RouteTabPanel.module.scss
  src/components/Route/RouteTabPanel/RouteTabPanel.tsx
  src/types/route.ts
Labels: feat

#160 Feat: create real time saving in votememo
  package-lock.json
  package.json
  src/api/vote.ts
  src/components/BottomSlide/BottomSlide.tsx
  src/components/ButtonsInAddingCandidate/SelectButton/SelectButton.tsx
  src/components/CandidatesMap/CandidatesMapBody/CandidatesMapBody.tsx
  src/components/CandidatesMap/CandidatesSlide/CandidatesSlide.tsx
  src/components/Vote/VoteBottomSlideContent/AddToJourney/AddToJourney.module.scss
  src/components/Vote/VoteBottomSlideContent/AddToJourney/AddToJourney.tsx
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/VoteMeatball.tsx
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.module.scss
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.tsx
  src/components/Vote/VoteContent/CandidateList/CandidateList.module.scss
  src/components/Vote/VoteContent/CandidateList/CandidateList.tsx
  src/components/Vote/VoteContent/VoteContent.module.scss
  src/components/Vote/VoteContent/VoteContent.tsx
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendList.module.scss
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendList.tsx
  src/components/Vote/VoteHeader/VoteHeader.module.scss
  src/components/Vote/VoteHeader/VoteHeader.tsx
  src/components/VoteMemo/MemoContent.tsx
  src/components/VoteMemo/MemoItem/MemoItem.tsx
  src/components/VoteTabPanel/TabsVoteCard/TabsVoteCard.module.scss
  src/components/VoteTabPanel/TabsVoteCard/TabsVoteCard.tsx
  src/components/VoteTabPanel/VoteTabPanel.tsx
  src/hooks/Votes/vote.ts
  src/hooks/useDebounce.ts
  src/hooks/useGetSelectedArray.ts
  src/hooks/useGetSelectedCandidates.ts
  src/hooks/useGetSelectedSet.ts
  src/mocks/handlers/vote.ts
  src/pages/Vote/Vote.tsx
  src/pages/Vote/VoteMemo/VoteMemo.tsx
  src/recoil/vote/selectPlace.ts
  src/recoil/vote/voteMemo.ts
  src/types/bottomSlide.ts
  src/types/vote.ts
Labels: feat

#168 Feat: connect msw add mockdata #149
  src/components/Auth/Alert/ExpireAlert.module.scss
  src/components/Auth/Alert/ExpireAlert.tsx
  src/components/Auth/FindPassword/FindPasswordForm.tsx
  src/components/Auth/FindPassword/Step/StepEmail.tsx
  src/components/Auth/FindPassword/Step/StepEmailSert.tsx
  src/components/Auth/Input/InputEmailSert.tsx
  src/components/Auth/Input/InputImage.tsx
  src/components/Auth/Login/LoginForm.tsx
  src/components/Auth/ModifyPassword/ModifyPasswordForm.tsx
  src/components/Auth/ModifyPassword/Step/StepOldPassword.tsx
  src/components/Auth/Signup/SignupForm.tsx
  src/components/Auth/Signup/Step/StepEmail.tsx
  src/components/Auth/Signup/Step/StepEmailSert.tsx
  src/components/User/EditProfileForm/EditProfileForm.tsx
  src/components/User/Profile/Profile.tsx
  src/hooks/User/useUser.ts
  src/pages/Auth/FindPassword/FindPassword.tsx
  src/pages/Auth/Login/Login.tsx
  src/pages/Auth/Signup/Signup.tsx
  src/pages/User/ModifyProfile/ModifyProfile.tsx
  src/pages/User/User.tsx
  src/pages/User/UserPrivacy/UserPrivacy.tsx
  src/types/auth.ts
  src/types/user.ts
  src/utils/formatDate.ts
Labels: feat

#171 Feat: connect api in region search page
  src/api/spaces.ts
  src/components/TripSpace/RegionSearchBox/RegionSearchBox.tsx
  src/hooks/Spaces/space.ts
  src/pages/RegionSearch/RegionSearch.tsx
  src/types/regionSearch.ts
  src/types/route.ts
  src/utils/getSpaceId.ts
Labels: feat

#172 Feat connect detail page api
  src/api/detail.ts
  src/assets/ic_google.svg
  src/chakra/chakraCustomTheme.ts
  src/chakra/drawerCustom.ts
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationSlide.tsx
  src/components/Detail/Contents/Contents.tsx
  src/components/Detail/Contents/Information/BasicInformation/BasicInformation.tsx
  src/components/Detail/Contents/Information/BasicInformation/MapInDetail/MapInDetail.tsx
  src/components/Detail/Contents/Information/BasicInformation/MapModal/MapModal.module.scss
  src/components/Detail/Contents/Information/BasicInformation/MapModal/MapModal.tsx
  src/components/Detail/Contents/Information/Information.tsx
  src/components/Detail/Contents/Information/Others/OtherCard/OtherCard.module.scss
  src/components/Detail/Contents/Information/Others/OtherCard/OtherCard.tsx
  src/components/Detail/Contents/Information/Others/Others.tsx
  src/components/Detail/Contents/Information/ShortReveiws/ShortReviews.tsx
  src/components/Detail/Contents/Review/Review.module.scss
  src/components/Detail/Contents/Review/Review.tsx
  src/components/Detail/Contents/Reviews/Reviews.tsx
  src/components/Detail/Main/ImageSwiper/Swiper.tsx
  src/components/Detail/Main/Main.module.scss
  src/components/Detail/Main/Main.tsx
  src/components/Detail/Main/Title/Title.tsx
  src/components/Detail/Navigation/Navigation.module.scss
  src/hooks/Detail/usePlaces.ts
  src/hooks/Detail/useReviews.ts
  src/hooks/Detail/useSpaces.ts
  src/hooks/Detail/useWish.ts
  src/hooks/Places/usePlaces.ts
  src/pages/Detail/Detail.tsx
  src/recoil/detail/detail.ts
  src/types/detail.ts
  tsconfig.json
Labels: feat

#174 Feat: add exception logic #164
  src/components/Alarm/Back/Back.module.scss
  src/components/Modal/FullMembers/FullMembers.module.scss
  src/components/Modal/FullMembers/FullMembers.tsx
  src/components/Modal/Invitation/Invitation.tsx
  src/components/SideBar/SideBar.tsx
  src/components/SideBar/TravelList/TravelList.tsx
  src/mocks/handlers/sidebar.ts
  src/pages/Home/Home.tsx
  src/recoil/fullmember/fullmember.ts
  src/types/Invitation.ts
  src/types/sidebar.ts
Labels: feat

#176 feat add meta data #175
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  public/vite.svg
  src/assets/alarm/alarmBlackBell.png
  src/assets/alarm/alarmWhiteBell.png
  src/assets/fonts/SUIT-Variable.ttf
  src/assets/react.svg
  src/hooks/test.tsx
  src/main.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/utils/getTitle.ts
Labels: feat

#178 177 feat add s3 api apply presigned url
  src/api/s3.ts
  src/components/Auth/Input/InputImage.tsx
  src/components/Auth/Signup/SignupForm.tsx
  src/components/Auth/Signup/Step/StepProfile.tsx
  src/components/User/EditProfileForm/EditProfileForm.tsx
  src/components/User/MypageList/MypageList.module.scss
  src/pages/User/User.module.scss
  src/types/auth.ts
  src/types/s3.ts
Labels: feat

#179 Feat: create wishes api
  src/api/detail.ts
  src/components/Detail/Contents/Information/BasicInformation/BasicInformation.tsx
  src/components/Detail/Contents/Information/BasicInformation/MapInDetail/MapInDetail.tsx
  src/components/Detail/Contents/Information/BasicInformation/MapModal/MapModal.tsx
  src/components/Detail/Contents/Information/Information.tsx
  src/components/Detail/Contents/Review/ReviewImageSlider/ReviewImageSlider.tsx
  src/components/Detail/Main/ImageSwiper/Swiper.tsx
  src/components/Detail/Main/Main.tsx
  src/components/Detail/Main/Title/Title.tsx
  src/components/Detail/Navigation/MeatballBottomSlide/MeatballBottomSlide.tsx
  src/components/WishBtn/WishBtn.tsx
  src/hooks/Detail/useWish.ts
  src/pages/Detail/Detail.tsx
  src/types/detail.ts
Labels: feat

#183 Feat: connect api with react-query in Vote
  src/api/vote.ts
  src/components/ButtonsInAddingCandidate/SelectButton/SelectButton.tsx
  src/components/CandidatesMap/CandidatesMapBody/CandidatesMapBody.tsx
  src/components/CandidatesMap/CandidatesSlide/CandidatesSlide.tsx
  src/components/CandidatesMap/MapPins/MapPinCommon.module.scss
  src/components/CandidatesMap/MapPins/MapPinCommon.tsx
  src/components/CandidatesMap/MapPins/MapPinNumber.tsx
  src/components/MapZoomIn/RouteMapBody/RouteMapBody.tsx
  src/components/Route/MapInTrip/MapInTrip.tsx
  src/components/Vote/DeleteCandidatesButton/DeleteCandidatesButton.tsx
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/VoteMeatball.tsx
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.module.scss
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.tsx
  src/components/Vote/VoteContent/CandidateList/CandidateList.tsx
  src/components/Vote/VoteContent/VoteContent.tsx
  src/components/VoteMemo/MemoContent.tsx
  src/components/VoteMemo/MemoItem/MemoItem.module.scss
  src/components/VoteMemo/MemoItem/MemoItem.tsx
  src/components/VoteTabPanel/VoteTabPanel.tsx
  src/hooks/Votes/useRankCalculator.ts
  src/hooks/Votes/vote.ts
  src/hooks/useGetSelectedArray.ts
  src/main.tsx
  src/mocks/handlers/vote.ts
  src/pages/Vote/Vote.tsx
  src/pages/Vote/VoteMemo/VoteMemo.tsx
  src/recoil/vote/selectPlace.ts
  src/recoil/vote/showResults.ts
  src/types/vote.ts
Labels: feat

#185 Fix: hotfix scroll sticky #66
  src/components/Route/DayNavigationBar/DayNavigationBar.module.scss
  src/components/Route/RouteTabPanel/RouteTabPanel.module.scss
  src/components/VoteTabPanel/VoteTabPanel.module.scss
  src/pages/Trip/Trip.module.scss
Labels: hotfix

#188 Refactor: home page detail
  src/api/home.ts
  src/assets/homeIcons/home/fireImoji.svg
  src/assets/homeIcons/home/musicImoji.svg
  src/assets/homeIcons/home/snowmanImoji.svg
  src/components/ButtonsInAddingCandidate/AddToCandidateButton/AddToCandidateButton.tsx
  src/components/ButtonsInAddingCandidate/SelectButton/SelectButton.tsx
  src/components/Home/TripSpaceAtHome/TripSpaceItem/TripSpaceItem.module.scss
  src/components/Home/TripSpaceAtHome/TripSpaceItem/TripSpaceItem.tsx
  src/components/Home/VoteAtHome/VoteAtHome.tsx
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.tsx
  src/components/Route/AddPlace/AddPlace.tsx
  src/components/SearchFromHome/MapHeader/MapHeader.module.scss
  src/components/SearchFromHome/MapHeader/MapHeader.tsx
  src/components/SearchFromHome/SearchBar/SearchBar.module.scss
  src/components/SearchFromHome/SearchBar/SearchBar.tsx
  src/components/SearchFromHome/SearchHome/SearchHome.module.scss
  src/components/SearchFromHome/SearchList/SearchList.tsx
  src/components/SearchFromHome/SearchList/Tabs/Tabs.tsx
  src/main.tsx
  src/pages/SearchFromHome/SearchFromHome.tsx
  src/types/home.ts
Labels: refactor

#190 Feat: add route optimizing function #186
  src/components/Route/DayRoute/DayRoute.module.scss
  src/components/Route/DayRoute/DayRoute.tsx
  src/utils/optimizePlace.ts
Labels: feat

#191 Feat: connect POST API
  src/api/detail.ts
  src/api/vote.ts
  src/assets/tripHome.svg
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationListItem/RegistrationListItem.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationModal/RegistrationModal.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationSlide.module.scss
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationSlide.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationTripSpace/RegistrationTripSpace.module.scss
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationTripSpace/RegistrationTripSpace.tsx
  src/components/Detail/Contents/Contents.tsx
  src/components/Detail/Contents/Information/Information.tsx
  src/components/Detail/Contents/Information/Others/OtherCard/OtherCard.tsx
  src/components/Detail/Contents/Information/Others/Others.tsx
  src/components/Detail/Contents/Information/ShortReveiws/ShortReviews.tsx
  src/components/Detail/Contents/ReviewBottomSlide/DateScrollPicker/DateScrollPicker.tsx
  src/components/Detail/Contents/ReviewBottomSlide/DateWrapper/DateWrapper.tsx
  src/components/Detail/Contents/ReviewBottomSlide/InputWrapper/InputWrapper.tsx
  src/components/Detail/Contents/ReviewBottomSlide/ReviewBottomSlide.tsx
  src/components/Detail/Contents/ReviewBottomSlide/StarsWrapper/StarsWrapper.tsx
  src/components/Detail/Contents/Reviews/Reviews.tsx
  src/components/Detail/Navigation/MeatballBottomSlide/MeatballBottomSlide.tsx
  src/hooks/Detail/useReviews.ts
  src/hooks/Votes/vote.ts
  src/pages/Detail/Detail.tsx
  src/recoil/detail/detail.ts
  src/types/detail.ts
  src/types/sidebar.ts
  src/types/vote.ts
Labels: feat

#187 Feat: apply infinite scroll connect myspacemyreview #169
  package-lock.json
  package.json
  src/api/review.ts
  src/api/spaces.ts
  src/assets/icons/city_default.svg
  src/assets/spinner.gif
  src/components/Auth/Input/Input.module.scss
  src/components/MySpaceBody/MySpaceBody.tsx
  src/components/MySpaceBody/MySpaceList/MySpaceList.module.scss
  src/components/MySpaceBody/MySpaceList/MySpaceList.tsx
  src/components/MySpaceBody/Tab/Tab.tsx
  src/components/Route/ObserveTarget/ObserveTarget.module.scss
  src/components/Route/ObserveTarget/ObserveTarget.tsx
  src/components/User/Mywork/Mywork.module.scss
  src/components/User/Profile/Profile.module.scss
  src/components/User/Profile/Profile.tsx
  src/hooks/Spaces/useSpaces.ts
  src/hooks/User/useMyReview.ts
  src/hooks/useInfiniteScroll.ts
  src/mocks/handlers/auth.ts
  src/pages/User/MyReview/MyReview.module.scss
  src/pages/User/MyReview/MyReview.tsx
  src/types/myReview.ts
  src/types/user.ts
Labels: feat

#194 Feat: add branch process in trip page
  src/api/spaces.ts
  src/chakra/avatarCustom.ts
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/MapZoomIn/RouteMapSlide/RouteMapSlide.tsx
  src/components/Route/DayRoute/DayRoute.tsx
  src/components/Route/DeletePlacesModal/DeletePlacesModal.tsx
  src/components/Route/DraggablePlaceCard/DraggablePlaceCard.tsx
  src/components/Route/MapInTrip/MapInTrip.tsx
  src/components/Route/RouteTabPanel/RouteTabPanel.tsx
  src/components/TripSpace/EditTripSpace/EditTripSpace.tsx
  src/components/TripSpace/FriendList/FriendList.module.scss
  src/components/TripSpace/FriendList/FriendList.tsx
  src/hooks/Spaces/space.ts
  src/hooks/useGoLogin.ts
  src/main.tsx
  src/pages/Calendar/Calendar.tsx
  src/pages/MapZoomIn/MapZoomIn.tsx
  src/pages/RegionSearch/RegionSearch.tsx
  src/pages/Trip/CheckTrip.tsx
  src/pages/Trip/Trip.module.scss
  src/pages/Trip/Trip.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/types/modal.ts
  src/types/route.ts
  src/utils/checkDday.ts
  src/utils/formatDate.ts
  src/utils/getMapCenter.ts
  src/utils/optimizePlace.ts
Labels: feat, fix, design

#197 Fix: hotfix route optimization #196
  src/utils/optimizePlace.ts
Labels: hotfix

#199 Feat: add password input in withdrawal #198
  src/api/auth.ts
  src/pages/Auth/Withdrawal/Withdrawal.module.scss
  src/pages/Auth/Withdrawal/Withdrawal.tsx
Labels: feat

#201 Feat: connect S3
  src/api/s3.ts
  src/components/Detail/Contents/ReviewBottomSlide/ImagesWrapper/ImagesWrapper.module.scss
  src/components/Detail/Contents/ReviewBottomSlide/ImagesWrapper/ImagesWrapper.tsx
  src/components/Detail/Contents/ReviewBottomSlide/ReviewBottomSlide.tsx
  src/components/User/EditProfileForm/EditProfileForm.tsx
  src/main.tsx
Labels: feat

#205 Feat: fix dynamic title #181
  src/components/Head/Head.tsx
  src/routes/MainRouter/MainRouter.tsx
  src/utils/getTitle.ts
Labels: fix

#209 200 feat seperate api request to authts
  src/api/auth.ts
  src/components/Auth/Input/InputEmail.tsx
  src/components/Auth/Input/InputEmailSert.tsx
  src/components/Auth/Input/InputNickname.tsx
  src/components/Auth/Login/LoginForm.tsx
  src/components/Auth/Login/LoginInput/InputEmail.tsx
  src/pages/Auth/Login/Login.tsx
  src/pages/Auth/Withdrawal/Withdrawal.tsx
  src/pages/User/UserPrivacy/UserPrivacy.tsx
Labels: refactor

#215 Feat: add location utils
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/Home/TripSpaceAtHome/NullTrip/NullTrip.module.scss
  src/components/Home/TripSpaceAtHome/TripSpaceItem/TripSpaceItem.module.scss
  src/components/Home/VoteAtHome/VoteAtHome.tsx
  src/pages/Wishes/Wishes.tsx
Labels: feat

#217 Fix: error fixed and modify feature
  src/api/detail.ts
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationTripSpace/RegistrationTripSpace.tsx
  src/components/Detail/Contents/Information/BasicInformation/MapInDetail/MapInDetail.tsx
  src/components/Detail/Contents/Information/BasicInformation/MapModal/MapModal.tsx
  src/components/Detail/Contents/Review/Review.tsx
  src/components/Detail/Main/Title/Title.tsx
  src/components/Detail/Navigation/MeatballBottomSlide/MeatballBottomSlide.tsx
  src/components/WishBtn/WishBtn.module.scss
  src/components/WishBtn/WishBtn.tsx
  src/hooks/Detail/useReviews.ts
  src/hooks/useDebounce.ts
  src/pages/Detail/Detail.tsx
Labels: feat

#219 Feat: home login modal
  src/api/detail.ts
  src/components/Home/RecommendedItemList/RecommendedItem/RecommendedItem.tsx
  src/components/Home/TripSpaceAtHome/NullTrip/NullTrip.module.scss
  src/components/Home/TripSpaceAtHome/NullTrip/NullTrip.tsx
  src/components/Home/VoteAtHome/VoteCard/CardNull/CardNull.module.scss
  src/components/Home/VoteAtHome/VoteCard/CardNull/CardNull.tsx
  src/components/SearchFromHome/SearchHome/HotItems/HotItem/HotItem.tsx
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItem/MapItem.module.scss
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItem/MapItem.tsx
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.tsx
  src/components/WishBtn/WishBtn.tsx
  src/components/WishItem/WishItem.tsx
  src/hooks/Detail/useWish.ts
  src/pages/Wishes/Wishes.module.scss
  src/pages/Wishes/Wishes.tsx
Labels: feat

#221 #165 feat connect alarm api
  public/firebase-messaging-sw.js
  src/api/notification.ts
  src/components/Alarm/Alarm.module.scss
  src/components/Alarm/Alarm.tsx
  src/components/Alarm/TabCapsule/Content/Content.module.scss
  src/components/Alarm/TabCapsule/Content/Content.tsx
  src/components/Alarm/TabCapsule/TabCapsule.tsx
  src/components/Home/TabBar/TabBar.tsx
  src/components/Modal/Invitation/Invitation.tsx
  src/components/SideBar/TravelList/TravelList.tsx
  src/components/User/MypageList/MypageList.tsx
  src/firebase/messaging-init-in-sw.ts
  src/hooks/Notification/useNotification.ts
  src/pages/Home/Home.tsx
  src/pages/Trip/Trip.tsx
  src/types/alarm.ts
  src/types/notification.ts
  src/utils/parsingAlarm.ts
Labels: feat

#213 211 fix fix code in vote for matching type
  src/App.tsx
  src/api/vote.ts
  src/components/ButtonsInAddingCandidate/AddToCandidateButton/AddToCandidateButton.tsx
  src/components/CandidatesMap/CandidatesMapBody/CandidatesMapBody.tsx
  src/components/CandidatesMap/CandidatesSlide/CandidatesSlide.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationListItem/RegistrationListItem.tsx
  src/components/Detail/BottomFixedBtn/RegistrationSlide/RegistrationSlide.tsx
  src/components/Vote/CreateVoteModal/CreateVoteModal.tsx
  src/components/Vote/DeleteCandidatesButton/DeleteCandidatesButton.tsx
  src/components/Vote/VoteBottomSlideContent/AddCandidate/AddCandidate.tsx
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/VoteMeatball.tsx
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.module.scss
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.tsx
  src/components/Vote/VoteContent/CandidateList/CandidateList.tsx
  src/components/Vote/VoteContent/VoteContent.tsx
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendItem/VoteRecommendItem.tsx
  src/components/VoteMemo/MemoItem/MemoItem.tsx
  src/components/VoteTabPanel/TabsVoteCard/TabsVoteCard.module.scss
  src/components/VoteTabPanel/TabsVoteCard/TabsVoteCard.tsx
  src/components/VoteTabPanel/VoteTabPanel.module.scss
  src/components/VoteTabPanel/VoteTabPanel.tsx
  src/hooks/Votes/vote.ts
  src/pages/CandidatesMap/CandidatesMap.tsx
  src/pages/Vote/Vote.tsx
  src/pages/Vote/VoteMemo/VoteMemo.tsx
  src/recoil/vote/selectPlace.ts
  src/recoil/vote/showResults.ts
  src/routes/MainRouter/MainRouter.tsx
  src/types/vote.ts
Labels: fix

#223 Fix remove cookie try1 #222
  src/components/Modal/Invitation/Invitation.tsx
Labels: fix

#226 Feat: fix exception logic in notification #225
  src/components/Alarm/TabCapsule/Content/Content.tsx
  src/components/Alarm/TabCapsule/TabCapsule.tsx
  src/components/Home/TabBar/TabBar.tsx
  src/components/SideBar/TravelList/TravelList.tsx
  src/firebase/messaging-init-in-sw.ts
  src/hooks/Notification/useNotification.ts
  src/pages/Home/Home.tsx
  src/pages/Trip/Trip.tsx
  src/types/alarm.ts
  src/utils/parsingAlarm.ts
Labels: fix

#227 Feat: seperate api request to auth
  src/api/auth.ts
  src/api/user.ts
  src/components/Auth/Signup/SignupForm.tsx
  src/components/Auth/Signup/Step/StepEmail.tsx
  src/components/Auth/Signup/Step/StepEmailSert.tsx
  src/components/MySpaceBody/MySpaceList/MySpaceList.module.scss
  src/components/MySpaceBody/MySpaceList/MySpaceList.tsx
  src/pages/Auth/Login/Login.tsx
  src/pages/User/MyReview/MyReview.tsx
  src/pages/User/User.tsx
  src/pages/User/UserPrivacy/UserPrivacy.tsx
  src/utils/formatDate.ts
Labels: feat

#231 Feat: seperate api request to auth
  public/city_default.svg
  public/profile_default.svg
  src/api/auth.ts
  src/assets/icons/profile_default.svg
  src/components/Alarm/TabCapsule/Content/Content.tsx
  src/components/Auth/FindPassword/FindPasswordForm.tsx
  src/components/Auth/FindPassword/Step/StepEmail.tsx
  src/components/Auth/FindPassword/Step/StepEmailSert.tsx
  src/components/Auth/ModifyPassword/ModifyPasswordForm.tsx
  src/components/Auth/ModifyPassword/Step/StepOldPassword.tsx
  src/components/Auth/Signup/Step/StepProfile.tsx
  src/components/MySpaceBody/MySpaceList/MySpaceList.tsx
  src/components/User/EditProfileForm/EditProfileForm.tsx
  src/components/User/Profile/Profile.tsx
  src/pages/User/MyReview/MyReview.tsx
Labels: feat, refactor

#233 Feat: axios error handling
  src/api/detail.ts
  src/api/review.ts
  src/assets/logo_yanolja.svg
  src/components/Detail/BottomFixedBtn/BottomFixedBtn.tsx
  src/components/Detail/Contents/Contents.tsx
  src/components/Detail/Contents/Information/BasicInformation/BasicInformation.module.scss
  src/components/Detail/Contents/Information/Information.module.scss
  src/components/Detail/Contents/Information/Information.tsx
  src/components/Detail/Contents/Information/ShortReveiws/ShortReviews.module.scss
  src/components/Detail/Contents/Information/ShortReveiws/ShortReviews.tsx
  src/components/Detail/Contents/ReviewBottomSlide/ReviewBottomSlide.tsx
  src/components/Detail/Contents/Reviews/Reviews.module.scss
  src/components/Detail/Contents/Reviews/Reviews.tsx
  src/components/Detail/Main/Title/Title.tsx
  src/components/Detail/Navigation/MeatballBottomSlide/MeatballBottomSlide.tsx
  src/hooks/useInfiniteScroll.ts
Labels: feat

#235 Fix: wishButton
  src/api/wishes.ts
  src/components/ButtonsInAddingCandidate/AddToCandidateButton/AddToCandidateButton.tsx
  src/components/Home/RecommendedItemList/RecommendedItem/RecommendedItem.module.scss
  src/components/Home/TripSpaceAtHome/TripSpaceItem/TripSpaceItem.module.scss
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.module.scss
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.tsx
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItem/MapItem.module.scss
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.module.scss
  src/components/SearchFromHome/SearchList/SearchList.module.scss
  src/components/SearchFromHome/SearchList/SearchList.tsx
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.tsx
  src/components/WishBtn/WishBtn.tsx
  src/hooks/Detail/useWish.ts
  src/pages/Wishes/Wishes.tsx
  src/types/home.ts
  src/utils/translateSearchData.ts
Labels: feat

#239 Feat connect api to edit journeys
  src/api/spaces.ts
  src/api/vote.ts
  src/components/Route/AddPlace/AddPlace.tsx
  src/components/Route/AddPlace/FromVote/CompletedVote/CompletedVote.tsx
  src/components/Route/AddPlace/FromVote/InProgressVote/InProgressVote.tsx
  src/components/Route/AddPlace/FromVote/PlaceList/PlaceList.tsx
  src/components/Route/AddPlace/FromVote/VoteCard/VoteCard.tsx
  src/components/Route/DayMove/DayMove.tsx
  src/components/Route/DayRoute/DayRoute.tsx
  src/components/Route/DeletePlacesModal/DeletePlacesModal.tsx
  src/components/Route/DraggablePlaceCard/DraggablePlaceCard.tsx
  src/components/Route/EmptyDate/EmptyDate.tsx
  src/components/Route/PlaceCard/PlaceCard.module.scss
  src/components/Route/RouteTabPanel/RouteTabPanel.tsx
  src/components/TripSpace/FriendList/FriendList.tsx
  src/components/TripSpace/LeaveTripModal/LeaveTripModal.tsx
  src/hooks/Spaces/space.ts
  src/pages/AddPlaceFromVote/AddPlaceFromVote.module.scss
  src/pages/AddPlaceFromVote/AddPlaceFromVote.tsx
  src/pages/Calendar/Calendar.tsx
  src/pages/RegionSearch/RegionSearch.tsx
  src/pages/Trip/Trip.module.scss
  src/pages/Trip/Trip.tsx
  src/recoil/ spaces/selectPlace.ts
  src/types/modal.ts
  src/types/route.ts
  src/utils/checkDday.ts
  src/utils/formatJourneyData.ts
  src/utils/getMapCenter.ts
Labels: feat

#242 224 feat get rank in vote page
  src/api/vote.ts
  src/components/Route/AddPlace/FromVote/VoteCard/VoteCard.tsx
  src/components/Vote/DeleteCandidatesButton/DeleteCandidatesButton.tsx
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/VoteMeatball.tsx
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.module.scss
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.tsx
  src/components/Vote/VoteContent/CandidateList/CandidateList.tsx
  src/components/Vote/VoteContent/VoteContent.tsx
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendList.tsx
  src/components/Vote/VoteHeader/VoteHeader.tsx
  src/components/VoteTabPanel/TabsVoteCard/TabsVoteCard.tsx
  src/components/VoteTabPanel/VoteTabPanel.tsx
  src/hooks/Votes/useRankCalculator.ts
  src/hooks/Votes/vote.ts
  src/pages/Vote/Vote.tsx
  src/pages/Vote/VoteMemo/VoteMemo.tsx
  src/recoil/vote/showResults.ts
  src/types/vote.ts
Labels: feat

#244 Feat: trip connect wish
  src/components/ButtonsInAddingCandidate/AddToCandidateButton/AddToCandidateButton.tsx
  src/components/ButtonsInAddingCandidate/SelectButton/SelectButton.tsx
  src/components/Home/TripSpaceAtHome/TripSpaceAtHome.tsx
  src/components/Home/VoteAtHome/VoteAtHome.tsx
  src/components/Route/AddPlace/AddPlace.tsx
  src/components/SearchFromHome/SearchList/DateFilter/DateFilter.module.scss
  src/components/SearchFromHome/SearchList/DateFilter/DateFilter.tsx
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.module.scss
  src/components/SearchFromHome/SearchList/SearchList.tsx
  src/components/VoteMemo/MemoItem/MemoItem.tsx
  src/recoil/vote/selectPlace.ts
Labels: feat

#243 Feat: connect API in my review
  src/api/detail.ts
  src/components/BottomSlide/BottomSlide.module.scss
  src/components/MyReview/ActionList/ActionList.tsx
  src/components/MyReview/EditReviewBottomSlide/DateBottomSlide/DateBottomSlide.module.scss
  src/components/MyReview/EditReviewBottomSlide/DateBottomSlide/DateBottomSlide.tsx
  src/components/MyReview/EditReviewBottomSlide/DateScrollPicker/DateScrollPicker.module.scss
  src/components/MyReview/EditReviewBottomSlide/DateScrollPicker/DateScrollPicker.tsx
  src/components/MyReview/EditReviewBottomSlide/DateWrapper/DateWrapper.module.scss
  src/components/MyReview/EditReviewBottomSlide/DateWrapper/DateWrapper.tsx
  src/components/MyReview/EditReviewBottomSlide/EditReviewBottomSlide.module.scss
  src/components/MyReview/EditReviewBottomSlide/EditReviewBottomSlide.tsx
  src/components/MyReview/EditReviewBottomSlide/ImagesWrapper/ImagesWrapper.module.scss
  src/components/MyReview/EditReviewBottomSlide/ImagesWrapper/ImagesWrapper.tsx
  src/components/MyReview/EditReviewBottomSlide/InputWrapper/InputWrapper.module.scss
  src/components/MyReview/EditReviewBottomSlide/InputWrapper/InputWrapper.tsx
  src/components/MyReview/EditReviewBottomSlide/StarsWrapper/StarsWrapper.module.scss
  src/components/MyReview/EditReviewBottomSlide/StarsWrapper/StarsWrapper.tsx
  src/hooks/User/useMyReview.ts
  src/pages/User/MyReview/MyReview.tsx
  src/types/detail.ts
  src/types/myReview.ts
Labels: feat

#245 228 feat add isalarmon api
  public/firebase-messaging-sw.js
  src/api/notification.ts
  src/components/User/MypageList/MypageList.tsx
  src/firebase/messaging-init-in-sw.ts
  src/hooks/Notification/useNotification.ts
  src/hooks/User/useUser.ts
  src/pages/User/User.tsx
  src/recoil/user/user.ts
  src/types/sidebar.ts
  src/utils/parsingAlarm.ts
Labels: feat

#246 206 middeploy
  jest.setup.ts
  src/api/auth.ts
  src/pages/User/UserPrivacy/UserPrivacy.tsx
  src/utils/checkDday.test.ts
  src/utils/formatDate.test.ts
  src/utils/formatDate.ts
  src/utils/inputValidation.test.ts
Labels: feat

#247 Hotfix: change mothod for kakao login
  src/api/auth.ts
Labels: feat

#253 Hotfix: fix kakao login
  src/api/auth.ts
  src/pages/Auth/Login/Login.tsx
Labels: feat, hotfix

#256 Feat: add link to home #255
  src/pages/Auth/Login/Login.tsx
Labels: feat

#259 Fix: fix exception notidata #251
  index.html
  public/Lottie.gif
  src/App.tsx
  src/components/Alarm/TabCapsule/TabCapsule.tsx
  src/components/Home/TabBar/TabBar.tsx
  src/custom.d.ts
Labels: fix

#257 Feat: complete map page
  src/api/spaces.ts
  src/components/MapZoomIn/RouteMapBody/RouteMapBody.tsx
  src/components/Route/DayRoute/DayRoute.tsx
  src/components/Route/MapInTrip/MapInTrip.tsx
  src/components/Route/RouteTabPanel/RouteTabPanel.tsx
  src/hooks/Spaces/space.ts
  src/pages/MapZoomIn/MapZoomIn.tsx
  src/pages/Trip/CheckTrip.tsx
  src/pages/Trip/Trip.tsx
Labels: feat, fix

#265 Feat: reflect qa
  src/components/Detail/BottomSlideDetail/BottomSlideDetail.tsx
  src/components/Detail/Contents/Information/BasicInformation/MapModal/MapModal.tsx
  src/components/Detail/Contents/Information/Information.tsx
  src/components/Detail/Contents/ReviewBottomSlide/ReviewBottomSlide.tsx
  src/components/Detail/Main/ImageSwiper/Swiper.tsx
  src/components/Detail/Main/Main.tsx
  src/components/Detail/Main/Title/Title.tsx
  src/components/Detail/Main/Title/TitleWishBtn/TitleWishBtn.tsx
  src/components/WishBtn/WishBtn.tsx
  src/pages/Detail/Detail.tsx
  src/recoil/detail/detail.ts
Labels: feat

#266 Fix: fix QA
  src/components/Home/TripSpaceAtHome/TripSpaceItem/TripSpaceItem.tsx
Labels: fix

#267 feat: add test code #261
  src/utils/formatTimeAgo.test.ts
  src/utils/parseInviteCode.test.ts
  src/utils/parseInviteCode.ts
  src/utils/parsingAlarm.test.ts
Labels: fix, test

#263 Feat: add test code
  src/utils/titleCaseChange.test.ts
  src/utils/translateSearchData.test.ts
Labels: feat

#268 Fix debug candidate map pages
  src/assets/nullImg.png
  src/components/CandidatesMap/CandidatesMapBody/CandidatesMapBody.tsx
  src/components/CandidatesMap/CandidatesSlide/CandidatesSlide.tsx
  src/components/CandidatesMap/MapPins/MapPinActive.tsx
  src/components/CandidatesMap/MapPins/MapPinCommon.tsx
  src/components/Vote/VoteBottomSlideContent/AddToJourney/AddToJourney.tsx
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.tsx
  src/components/Vote/VoteContent/CandidateList/CandidateList.module.scss
  src/components/Vote/VoteContent/CandidateList/CandidateList.tsx
  src/components/Vote/VoteContent/VoteContent.tsx
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendItem/VoteRecommendItem.tsx
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendList.tsx
  src/components/Vote/VoteHeader/VoteHeader.tsx
  src/pages/CandidatesMap/CandidatesMap.tsx
  src/pages/Trip/Trip.tsx
  src/pages/Vote/Vote.tsx
  src/recoil/vote/addToJourney.ts
  src/types/vote.ts
Labels: fix

#274 Fix: detail link
  src/assets/homeIcons/search/favoriteNull.svg
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.tsx
  src/components/SearchFromHome/SearchList/SearchList.tsx
  src/components/WishItem/WishItem.tsx
  src/pages/SearchFromHome/SearchFromHome.tsx
  src/pages/Wishes/Wishes.tsx
Labels: fix

#275 Feat: qa develop
  src/App.tsx
  src/components/BottomSlide/BottomSlide.tsx
  src/components/Detail/BottomFixedBtn/BottomFixedBtn.tsx
  src/components/Detail/Contents/Information/ShortReveiws/ShortReviews.tsx
  src/components/Detail/Contents/Reviews/Reviews.tsx
  src/components/Detail/Main/SlideModal/SlideModal.module.scss
  src/components/Detail/Main/SlideModal/SlideModal.tsx
  src/components/Detail/Main/Title/TitleWishBtn/TitleWishBtn.tsx
  src/components/Detail/Navigation/MeatballBottomSlide/MeatballBottomSlide.tsx
  src/components/MyReview/EditReviewBottomSlide/EditReviewBottomSlide.tsx
  src/components/WishBtn/WishBtn.tsx
  src/pages/User/MyReview/MyReview.tsx
  src/sass/abstracts/_mixin.scss
  src/types/bottomSlide.ts
Labels: feat, fix

#276 Feat: fix split error & add toaset in modify password & add props cancel action
  src/components/AlertModal/AlertModal.tsx
  src/components/Auth/ModifyPassword/ModifyPasswordForm.tsx
  src/components/Auth/Signup/SignupForm.tsx
  src/pages/Auth/Withdrawal/Withdrawal.tsx
  src/types/vote.ts
Labels: feat

#278 Fix: search hot items detail link
  src/components/SearchFromHome/MapHeader/MapHeader.tsx
  src/components/SearchFromHome/SearchHome/HotItems/HotItem/HotItem.tsx
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.tsx
  src/pages/SearchFromHome/SearchFromHome.tsx
Labels: fix

#279 Feat: add journey in detail page
  src/components/Detail/BottomFixedBtn/BottomFixedBtn.tsx
  src/pages/Detail/Detail.tsx
  src/types/detail.ts
Labels: feat

#280 Fix: search home
  src/components/SearchFromHome/SearchHome/HotForTrip/HotForTrip.module.scss
  src/components/SearchFromHome/SearchHome/HotForTrip/HotForTrip.tsx
  src/components/SearchFromHome/SearchHome/SearchHome.tsx
  src/components/SearchFromHome/SearchList/SearchItem/SearchItem.tsx
Labels: fix

#281 Feat: add scroll to top logic show gnb login alert
  src/App.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.module.scss
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/custom.d.ts
  src/routes/MainRouter/MainRouter.tsx
Labels: feat, refactor

#282 Fix: search home
  src/components/Home/RecommendedItemList/RecommendedItemList.module.scss
  src/components/Home/RecommendedLocationList/RecommendedLocationList.module.scss
  src/components/Home/TripSpaceAtHome/TripSpaceAtHome.module.scss
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.module.scss
Labels: fix

#284 Fix: debug in vote page
  src/components/CandidatesMap/CandidatesSlide/CandidatesSlide.tsx
  src/components/Vote/VoteBottomSlideContent/VoteMeatball/VoteMeatball.tsx
  src/components/Vote/VoteContent/CandidateCard/CandidateCard.tsx
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendItem/VoteRecommendItem.module.scss
  src/components/Vote/VoteContent/VoteRecommendList/VoteRecommendItem/VoteRecommendItem.tsx
  src/components/VoteMemo/MemoItem/MemoItem.tsx
  src/components/VoteTabPanel/TabsVoteCard/TabsVoteCard.tsx
Labels: fix

#285 Fix: fix react query
  src/api/spaces.ts
  src/components/MapZoomIn/RouteMapSlide/RouteMapSlide.module.scss
  src/components/Route/DayMove/DayMove.tsx
  src/components/Route/DeletePlacesModal/DeletePlacesModal.tsx
  src/components/Route/RouteTabPanel/RouteTabPanel.tsx
  src/components/Vote/VoteBottomSlideContent/AddToJourney/AddToJourney.tsx
  src/hooks/Spaces/space.ts
  src/pages/AddPlaceFromVote/AddPlaceFromVote.tsx
  src/pages/RegionSearch/RegionSearch.tsx
  src/pages/Trip/CheckTrip.tsx
  src/pages/Trip/Trip.tsx
  src/recoil/spaces/trip.ts
  src/types/route.ts
Labels: feat, fix

#287 Feat: trip connect search
  src/components/ButtonsInAddingCandidate/AddToCandidateButton/AddToCandidateButton.tsx
  src/components/ButtonsInAddingCandidate/SelectButton/SelectButton.tsx
  src/components/SearchFromHome/SearchHome/SearchKeyword/SearchKeyword.module.scss
  src/recoil/vote/selectPlace.ts
Labels: feat

#289 Fix: trip
  src/components/Route/DayRoute/DayRoute.tsx
Labels: fix

#290 Feat: apply reactquery to auth request
  src/api/auth.ts
  src/components/Auth/FindPassword/FindPasswordForm.tsx
  src/components/Auth/FindPassword/Step/StepEmail.tsx
  src/components/Auth/FindPassword/Step/StepEmailSert.tsx
  src/components/Auth/Input/InputEmailSert.tsx
  src/components/Auth/Login/LoginForm.tsx
  src/components/Auth/ModifyPassword/ModifyPasswordForm.tsx
  src/components/Auth/ModifyPassword/Step/StepOldPassword.tsx
  src/components/Auth/Signup/SignupForm.tsx
  src/components/Auth/Signup/Step/StepEmail.tsx
  src/components/Auth/Signup/Step/StepEmailSert.tsx
  src/hooks/Auth/auth.ts
  src/hooks/Auth/useAuth.ts
  src/pages/Auth/Withdrawal/Withdrawal.tsx
  src/pages/User/UserPrivacy/UserPrivacy.tsx
  src/types/auth.ts
Labels: refactor

#293 Feat: others open
  src/components/Detail/Contents/Information/Information.tsx
  src/components/Detail/Contents/Information/Others/Others.tsx
Labels: feat

#292 Fix: home QA
  src/assets/homeIcons/home/searchIcon.svg
  src/components/Home/Onboarding/Onboarding.module.scss
  src/components/Home/TabBar/TabBar.module.scss
  src/components/Home/TabBar/TabBar.tsx
  src/components/Home/VoteAtHome/VoteCard/CardHaveVote/CardHaveVote.tsx
  src/components/SearchFromHome/MapHeader/MapHeader.module.scss
  src/components/SearchFromHome/SearchHome/HotItems/HotItems.module.scss
  src/components/SearchFromHome/SearchList/Map/MapItems/MapItems.module.scss
  src/components/WishItem/WishesHeader/WishesHeader.module.scss
Labels: fix

#294 Fix: fix design feature QA #291
  src/components/Alarm/TabCapsule/Content/Content.module.scss
  src/components/SideBar/SideBar.tsx
  src/components/SideBar/TravelList/TravelList.tsx
  src/types/sidebar.ts
Labels: fix
